### ISSUE TITLE
Crash when importing. UnboundLocalError

### ISSUE THREAD

**Issue by consolegrl** [SatyrDiamond/DawVert#11]
Crash when trying to convert flp to mmp

Commandline:
python dawvert_cmd.py -i WarZone-20.flp --samplefolder . -ot lmms -o warzone.mmp

`[plug-conv] Converting Slicer to Ninjas 2: plugin1005
Traceback (most recent call last):
  File "/home/user/src/DawVert/dawvert_cmd.py", line 101, in <module>
    core.convert_plugins(extra_json)
  File "/home/user/src/DawVert/functions/core.py", line 177, in convert_plugins
    CVPJ_C = plug_conv.convproj(convproj_j[0], platform_id, convproj_j[1], currentplug_output[3], currentplug_input[1], currentplug_output[1], currentplug_output[5], currentplug_output[6], extra_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/DawVert/functions/plug_conv.py", line 147, in convproj
    is_converted, plugintype = convertpluginconvproj(sep_pl_pc_out__plugins[out_getsupportedplugformat], cvpj_l, pluginid, plugintype, extra_json)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/DawVert/functions/plug_conv.py", line 93, in convertpluginconvproj
    isconverted = plugclassinfo[0].convert(cvpj_l, pluginid, plugintype, extra_json)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/DawVert/plugin_plugconv/vst2__i_sampler_slicer.py", line 19, in convert
    plugin_vst2.replace_data(cvpj_l, pluginid, 'name','any', 'Ninjas 2', 'chunk', data_nullbytegroup.make(ninjas2out), None)
  File "/home/user/src/DawVert/functions/plugin_vst2.py", line 90, in replace_data
    vst_cpuarch, vst_path, vst_name = find_path(in_name, platformtxt, bycat)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/user/DawVert/functions/plugin_vst2.py", line 75, in find_path
    vst_cpuarch, vst_path = find_locpath(out_paths)
                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/src/DawVert/functions/plugin_vst2.py", line 55, in find_locpath
    return vst_cpuarch, vst_path
           ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'vst_cpuarch' where it is not associated with a value`

**Comment by consolegrl** [comment]
Addendum, here is the file I was testing on, in case you'd like to test anything else with it. 
[WarZone.zip](https://github.com/SatyrDiamond/DawVert/files/12609926/WarZone.zip)
