### ISSUE TITLE
AttributeError: 'dawproject_lane' object has no attribute 'fadeTimeUnit'

### ISSUE THREAD

**Issue by ensonic** [SatyrDiamond/DawVert#19]
Running from:
```
commit 9275e0a8c9e0d94b2ca4d2bb03cfff7c4a15b419 (HEAD -> main, origin/main, origin/HEAD)
Author: SatyrDiamond <109001272+SatyrDiamond@users.noreply.github.com>
Date:   Wed Nov 6 21:05:03 2024 -0800
```

```
python3 dawvert_cmd.py -i 20241111.Collab.dawproject -ot flp -o 20241111.Collab.flp
DawVert: Daw Conversion Tool
   INFO |      plugins | Loaded 3 audiofile Plugins.
    INFO |      plugins | Loaded 10 audiocodecs Plugins.
    INFO |      plugins | Loaded 2 audioconv Plugins.
    INFO |      plugins | Loaded 46 input Plugins.
    INFO |      plugins | Loaded 33 plugconv Plugins.
    INFO |      plugins | Loaded 25 plugconv_ext Plugins.
    INFO |      plugins | Loaded 9 extplug Plugins.
    INFO |      plugins | Loaded 13 output Plugins.
    INFO |      plugins | Auto-Set input plugin: dawproject (DawProject)
    INFO |      plugins | Set output plugin: flp (FL Studio 20)
    INFO |      project | Group - id2
    INFO |      project | Track w/Pl - id9
    INFO |      project | Track w/Pl - id14
    INFO |      project | Track w/Pl - id19
    INFO |      project | Plugin - id24 - external:vst3
    INFO |  globalstore | extplug: Loaded database
 WARNING |      plugins | vst3: plugin not found in database: "565354734D617376616C68616C6C6173" from id
    INFO |      project | Group - id26
    INFO |      project | Track w/Pl - id33
    INFO |      project | Plugin - id38 - external:clap
    INFO |      project | Group - id41
    INFO |      project | Track w/Pl - id48
    INFO |      project | Plugin - id53 - external:clap
    INFO |      project | Track w/Pl - id55
    INFO |      project | Plugin - id60 - external:clap
    INFO |      project | SampleRef - audio/polarity kick 117.wav - /home/ensonic/projects/audio/DawVert/__samples_extracted/20241111.Collab/audio/polarity kick 117.wav
    INFO |      project | SampleRef - audio/Hhana10.wav - /home/ensonic/projects/audio/DawVert/__samples_extracted/20241111.Collab/audio/Hhana10.wav
Traceback (most recent call last):
  File "/home/ensonic/projects/audio/DawVert/dawvert_cmd.py", line 151, in <module>
    dawvert_core.parse_input(in_file, dawvert_core.config)
  File "/home/ensonic/projects/audio/DawVert/objects/core.py", line 298, in parse_input
    plug_obj.parse(self.convproj_obj, in_file, dv_config)
  File "/home/ensonic/projects/audio/DawVert/plugins/input/r_dawproject.py", line 373, in parse
    if clip.clips: do_clips(convproj_obj, track_obj, clip, clip.clips)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ensonic/projects/audio/DawVert/plugins/input/r_dawproject.py", line 298, in do_clips
    do_audioclip(convproj_obj, npa_obj, inclip.lanes)
  File "/home/ensonic/projects/audio/DawVert/plugins/input/r_dawproject.py", line 228, in do_audioclip
    if inclip.fadeTimeUnit == 'beats':
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dawproject_lane' object has no attribute 'fadeTimeUnit'
```

adding some logging to the code I get:
```
<objects.file_proj._dawproject.clips.dawproject_lane object at 0x7fc47810f110> {   'audio': None,
    'clips': None,
    'id': 'id117',
    'points': [   <objects.file_proj._dawproject.points.dawproject_points object at 0x7fc47810f1a0>],
    'track': '',
    'warps': <objects.file_proj._dawproject.clips.dawproject_warps object at 0x7fc47810f170>}
```

**Comment by ensonic** [comment]
Sorry, synced to head and now that issue is gone.

**Comment by ensonic** [comment]
Thanks!
