### ISSUE TITLE
crashed on convert "AttributeError: 'cvpj_project' object has no attribute 'filesearcher'"

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [SatyrDiamond/DawVert#25]
Traceback (most recent call last):
  File "C:\Users\Ascend\Executables\DawVert-main\dawvert_ui.py", line 126, in run
    dawvert_core.parse_input(in_file, dv_core.config_data)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\objects\core.py", line 320, in parse_input
    plug_obj.parse(self.convproj_obj, in_file, dv_config)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\plugins\input\mi_flp.py", line 879, in parse
    convproj_obj.sampleref__searchmissing(input_file)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\objects\convproj\project.py", line 469, in sampleref__searchmissing
    files = self.filesearcher.searchcache
            ^^^^^^^^^^^^^^^^^
AttributeError: 'cvpj_project' object has no attribute 'filesearcher'

Conversion: from FL-Studio to LMMS
OS: Windows 11 24H2
Python: 3.13.1

**Comment by ImGGAAVVIINN** [comment]
The old error is now gone, but a new one appeared

```Traceback (most recent call last):
  File "C:\Users\Ascend\Executables\DawVert-main\dawvert_ui.py", line 126, in run
    dawvert_core.parse_input(in_file, dv_core.config_data)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\objects\core.py", line 320, in parse_input
    plug_obj.parse(self.convproj_obj, in_file, dv_config)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\plugins\input\mi_flp.py", line 879, in parse
    convproj_obj.sampleref__searchmissing(input_file)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\objects\convproj\project.py", line 474, in sampleref__searchmissing
    sampleref_obj.search_local()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
TypeError: cvpj_sampleref.search_local() missing 1 required positional argument: 'dirpath'```

**Comment by SatyrDiamond** [comment]
did a commit to fix that in https://github.com/SatyrDiamond/DawVert/commit/49978e5b346b509bba23bad20ac36e57cedfe088
